# Generated by Django 2.2.12 on 2024-06-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=10, verbose_name='part')),
                ('question', models.TextField(verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add_time')),
                ('ch_date', models.DateTimeField(auto_now_add=True, verbose_name='ch_time')),
            ],
            options={
                'db_table': 'question_and_answer',
            },
        ),
    ]
